config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  
  get '/projects', to: 'static_pages#projects'
  get 'blog_posts/unpublished', to: 'blog_posts#unpublished'
  get 'blog_posts/preview', to: 'blog_posts#preview'
  
  resources :blog_posts do
    patch :toggle_published, to: 'blog_posts#toggle', as: 'toggle_published'
  end
  
  
  get '/admin_login', to: 'sessions#new'
  post '/admin_login', to: 'sessions#create'
  delete '/admin_logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  attr_accessor :content
  
  has_attached_file :title_image, styles: {
    square: '200x200#',
    medium: '250x140'
  }
  
  validates :title, presence: true
  validates :subtitle, presence: true
  validates :aws_obj_key, presence: true
  validates_attachment_content_type :title_image, :content_type => /\Aimage\/.*\Z/
  
  before_save :set_path_name, if: -> {new_record? || title_changed?}

  before_destroy :remove_files_from_aws
  
  def save_content_to_aws
    self.aws_obj_key = 'blog/' + self.title.gsub(" ", "-").downcase + '.md'
    
    object = fetch_s3_object
    
    object.put(body: self.content)
  end
  
  def fetch_content_from_aws
    object =  fetch_s3_object
    
    self.content = object.get.body.string
  end
  
  private
    def set_path_name
      self.path = title.downcase.gsub(" ", "-")
    end
    
    def remove_files_from_aws
      object = fetch_s3_object
      
      object.delete
    end
    
    def fetch_s3_object
      s3 = Aws::S3::Resource.new
      bucket = s3.bucket(ENV.fetch("PERSONAL_WEBSITE_BUCKET_NAME"))
      bucket.object(self.aws_obj_key)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  private
    def not_found
      raise ActionController::RoutingError.new('Not Found')
    end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :load_blog_post, only: [:show, :edit, :destroy, :update]
  before_action :require_admin_login, only: [:new, :create, :edit, :destroy, :unpublished, :toggle]
  
  def index
    @blog_posts = BlogPost.where(published: true)
                          .order(created_at: :desc)
                          .paginate(page: params[:page], per_page: 6)
  end
  
  def new
    @blog_post = BlogPost.new
  end
  
  def preview
    @blog_post = BlogPost.new(blog_post_params)
    
    render 'show'
  end
  
  def create
    @blog_post = BlogPost.new(blog_post_params)
    @blog_post.save_content_to_aws
    flash[:success] = "Post was uploaded successfully and is #{@blog_post.published? ? nil : "not"} published"
    
    @blog_post.save
    
    redirect_to blog_post_url @blog_post.path
  end
  
  def show
    @blog_post.fetch_content_from_aws
  end
  
  def edit
    @blog_post.fetch_content_from_aws
  end
  
  def update
    if @blog_post.update_attributes(blog_post_params)
      @blog_post.save_content_to_aws
      flash[:success] = "Post updated successfully"
      
      redirect_to blog_post_url @blog_post.path
    else
      flash[:error] = @blog_post.errors.full_messages.first
      render 'edit'
    end
  end
  
  def destroy
    @blog_post.destroy
    
    redirect_to blog_posts_url
  end
  
  def unpublished
    @blog_posts = BlogPost.where(published: false)
                  .order(created_at: :desc)
                  .paginate(page: params[:page], per_page: 6)
    
  end
  
  def toggle
    @blog_post = BlogPost.find_by(path: params[:blog_post_id])
    @blog_post.toggle!(:published)
    
    flash[:success] = "Post was #{@blog_post.published? ? nil : "un"}published"
    redirect_to blog_posts_url_where_visible
  end
  
  private
    
    def blog_post_params
      params.require(:blog_post).permit(:title, :subtitle, :content, :title_image, :published)
    end
    
    def load_blog_post
      @blog_post = BlogPost.find_by(path: params[:id]) or not_found
    end
    
    def require_admin_login
      redirect_to root_url unless session[:admin] == 1
    end
    
    def blog_posts_url_where_visible
      @blog_post.published? ? blog_posts_url : blog_posts_unpublished_url
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    if params[:admin_password] == ENV['ADMIN_PASSWORD']
      session[:admin] = 1
      flash[:success] = "Logged in as Admin"
      
      redirect_to blog_posts_url
    else
      flash.now[:error] = "Incorrect Password. If you are not the admin, don't try logging in"
    end
  end
  
  def destroy
    session.delete(:admin)
    
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def projects
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
require 'rouge/plugins/redcarpet'

module BlogPostsHelper
  
  
  def render_markdown(text)
    extras = {
       autolink: true,
       no_intra_emphasis: true,
       fenced_code_blocks: true,
       strikethrough: true,
       superscript: true,
       lax_spacing: true
     }
    
    markdown = Redcarpet::Markdown.new(CustomRender, extras)
    markdown.render(text).html_safe
  end
  
  def admin_logged_in?
    session[:admin] == 1
  end
  
  def post_date_format(date)
    date.strftime("%b %-d, %Y")
  end
  
  def opposite_of_published(blog_post) 
    blog_post.published? ? "Unpublish" : "Publish"
  end
  
  private
    class CustomRender < Redcarpet::Render::HTML
      include Rouge::Plugins::Redcarpet
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/blog_posts/_form.html.erb
<%= form_for(@blog_post, multipart: true, url: url) do |f| %>
    <div class="form-row">
        <div class="col-md-2 col-md-offset-3">
            <div class>
                <%= f.label :title_image %>
                <%= f.file_field :title_image %>
            </div>
        </div>
        
        <div class="col-md-2">
            <div class="form-group">        
                        <%= f.label :title  %>
                        <%= f.text_field :title, class: "form-control" %>
            </div> 
        </div>
        
        <div class="col-md-2">
            <div class="form-group">
                        <%= f.label :subtitle %>
                        <%= f.text_field :subtitle, class: "form-control" %>
            </div>
        </div>
    </div>
    <div class="form-row">
        <div class="col-md-6 col-md-offset-3">
            <div class="form-check">
                <%= f.check_box :published, class: "form-check-input" %>
                <%= f.label "Publish post on upload", class: "form-check-label" %>
            </div>
        </div>
    </div>
    <div class="form-row">
        <div class="col-md-6 col-md-offset-3">
            <div class="form-group">
            <%= f.text_area :content, class: "blog-content-input", placeholder: "Put blog markdown content here" %>
        </div>
    </div>
        
    <div class="row">
        <div class="col-md-9">
            <div class="btn-group pull-right">
                <%= link_to "Cancel", blog_posts_path, class: "btn btn-primary" %>
                <%= link_to "Preview", blog_posts_preview_path, class: "btn btn-primary", target: "_blank" %>
                <%= f.submit button_text, class: "btn btn-primary" %>
            </div>
        </div>
    </div>
<% end %>

app/views/blog_posts/_posts.html.erb
<div class="container">
  <% if admin_logged_in? %>
    <div class="row">
      <div class="col-md-4 pull-left">
         <div class="btn-group">
           <%= link_to "#{other_post_type} Posts", other_post_type_path, class: "btn btn-primary" %>
           <%= link_to "New Post", new_blog_post_path, class: "btn btn-primary" %>
         </div>  
      </div>
      <div class="col-md-4">
        <p class="admin-message-text"><%= admin_message %></p> 
      </div>
    </div>
   
  <% end %>
  
  <%= will_paginate @blog_posts, renderer: BootstrapPagination::Rails %>
  
  <% @blog_posts.each_slice(3) do |set_of_posts| %>
    <div class="row">
      <% set_of_posts.each do |blog_post| %>
        <div class="col-md-4 card-col">
          <div class="card text-center">
            <div class="card-img-container">
              <%= image_tag blog_post.title_image.url(:medium), class: "title-image" %>
            </div>
            
            <div class="card-body">
              <h5 class="card-title"><%= blog_post.title %></h5>
              <p class="card-text"><%= blog_post.subtitle %></p>
              <p class="card-text">Posted on: <%= post_date_format(blog_post.created_at) %></p>
              <%= link_to "Read More", blog_post_path(blog_post.path), class: "btn btn-lg btn-primary read-more-btn" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/blog_posts/edit.html.erb
<%= render 'form', button_text: "Update Post", url: blog_post_path(@blog_post.path) %>

app/views/blog_posts/index.html.erb
<%= render 'posts', other_post_type: "Unpublished", 
                    other_post_type_path: blog_posts_unpublished_path,
                    admin_message: "These posts are published"%>

app/views/blog_posts/new.html.erb
<%= render 'form', button_text: "Upload Post", url: blog_posts_path %>
        

app/views/blog_posts/show.html.erb
<div class="container">
    <div class="row blog-background">
        <div class="col-md-10 col-md-offset-1">
            <%= link_to blog_posts_path, class: "btn btn-default pull-left" do %>
              <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span> All Posts
            <% end %>
            <% if admin_logged_in? %>
                <div class='btn-group pull-right'>
                    <%= link_to "Edit", edit_blog_post_url(@blog_post.path), class: "btn btn-primary" %>
                    <%= link_to "Delete", blog_post_url(@blog_post.path), method: :delete, class: "btn btn-primary", data: { confirm: "Delete Cannot Be Undone. Are you sure?" } %>
                    <%= link_to opposite_of_published(@blog_post), blog_post_toggle_published_path(@blog_post.path), method: :patch, class: "btn btn-primary" %>
                </div>
            <% end %>
            <div class="page-header">
                <%= image_tag @blog_post.title_image.url(:medium), class: "thumbnail pull-left blog-img-title" %>
                <h1><%= @blog_post.title%></h1>
                <p><%= @blog_post.subtitle %></p>
            </div>
            
            
        </div>
    </div>  
    <div class="row">
        <div class="col-md-10 col-md-offset-1 blog-post-content">
            <%= render_markdown(@blog_post.content) %>
        </div>
    </div>      
</div>

app/views/blog_posts/unpublished.html.erb
<%= render 'posts', other_post_type: "Published", 
                    other_post_type_path: blog_posts_path,
                    admin_message: "These posts are not published"%> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eitan Bar-David</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<nav class="row navbar navbar-inverse">
  	  <div class="container-fluid">
  		    <div class="navbar-header">
  		      <%= link_to "Eitan Bar-David", root_url, class: "navbar-brand" %>
  		    </div>
  		    <ul class="nav navbar-nav navbar-right">
  		      <li><%= link_to projects_path do %>
  		        <span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span>  Projects
  		      <% end %></li>
  		      <li><%= link_to blog_posts_path do %>
  		        <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span> Blog
  		      <% end %></li>
  		      <li><%= link_to asset_path('eitan-bar-david-resume.pdf'), target: '_blank' do %>
  		        <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span> Resume
  		      <% end %></li>
  		      <li><%= mail_to "eitansbd@gmail.com", subject: "Connect" do %>
  		        <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Contact Me!
  		      <% end %>
  		      </li>
  		      <% if admin_logged_in? %>
  		      <li><%= link_to "Logout", admin_logout_url, method: :delete %></li>
  		      <% end %>
  		    </ul>
  
  	  </div>
  	</nav>
  	
  	<% flash.each do |msg_type, msg| %>
    	<div class="container">
    	  <div class="row">
    	     <div class="col-md-12">
    	       <div class="alert alert-<%= msg_type %>", role: "alert"><%= msg %></div>
    	     </div>
    	   </div>
    	</div>
    <% end %>
  	
  	<%= yield %>
  	
  	<div class="footer">
    	<div class="container">
  	  	 <div class="container-fluid text-center">
  			    <div class="row">
  		        <a href="https://github.com/eitansbd" target="_blank"><%= image_tag 'GitHub-Mark-64px.png', alt: "github", class: "footer-image" %></a>
  		        <a href="https://linkedin.com/in/eitanbardavid" target="_blank"><%= image_tag 'LI-In-Bug.png', class: "footer-image", alt: "linkedin" %></a>
  		    	</div>
  			</div>
  	  </div>
  	</div>
  </body>
</html>

app/views/static_pages/_video_modal.html.erb
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#<%= modal_name %>Modal">Demo Video</button>
                        
<div class="modal fade" id="<%= modal_name %>Modal" tabindex="-1" role="dialog" aria-labelledby="<%= modal_name %>ModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div align="center" class="embed-responsive embed-responsive-16by9">
                    <iframe width="420" height="315" class: "embed-responsive-item" controls autoplay
                        src="https://www.youtube.com/embed/<%= youtube_video_id %>">
                    </iframe>
                </div>
            </div>
        </div>
   </div>
</div>

app/views/static_pages/home.html.erb
<div class="container">
    <div class="jumbotron about-me">
        <div class="row">
        <div class="col-md-6 col-md-offset-1 vcenter about-me-text">
            <h2>Hi!</h2>
            <p class="personal-description">I am a Software Engineer with a passion for solving complex problems with simple solutions. I have experience building web apps with Ruby, Rails, JavaScript, and PostgreSQL and am constantly expanding my knowledge by experimenting and building projects. I recently received my bachelor's degree in Mechanical Engineering which gave me a strong foundation in math, mechanics, and electronics and continues to shape the way I think and solve problems. Check out the <%= link_to "projects page", projects_path %> for video demos of the applications I've built or the <%= link_to "blog page", blog_posts_path %> to see what I'm working on now.
            <p>
        </div><!--
        --><div class="col-md-4 vcenter">
            <span class="border"><%= image_tag 'profile_pic.jpg', class: "img-circle border border-primary", alt: "profile-pic", id: "profile-pic" %> </span>
        </div>
        </div>
    </div>
    
    <div class="row top-buffer contact-pitch">
        <div class="col-md-2 col-md-offset-2 vcenter float-right">
            <a class="btn btn-primary btn-block" href="mailto: eitansbd@gmail.com" role="button">Email Me!</a>
        </div>
        <div class="col-md-6 personal-facts vcenter">
            <p class="border border-primary">Whether you want to contact me about a job or just chat I'm always interested in meeting new people and collaborating on projects. Send me an email and I'll get back to you ASAP!</p>
        </div>
    </div>
</div>

app/views/static_pages/projects.html.erb
<div class="container">
    <div class="row">
        <div class="jumbotron">
            <h2>Keeper
                <div class="btn-group pull-right">
                    <%= link_to "Source Code", "https://github.com/Eitansbd/keeper", target: "_blank", class: "btn btn-primary" %>
                    <button type="button" class="btn btn-primary">Demo Coming Soon!</button>
                    <%= link_to "Project Website", "https://keeperfish.herokuapp.com/", target: "_blank", class: "btn btn-primary" %>
                </div>
            </h2>
            <div class="row top-buffer-sm">
                <div class="col-md-4">
                    <h4>Background</h4>
                    <p>I went on my first fishing trip when I was three and have been hooked ever since. This website combines my passion for fishing and software by providing a platform for anglers to share their fishing experiences and the fish that they've caught. After signing up, users can post reports of the fishing trips they've been on and add the weight, length, and an image of fish they caught to show off their catches and see how they stack up against other anglers. </p>
                </div>
                <div class="col-md-4">
                    <h4>Best Feature</h4>
                    <p>The homepage contains a table with the top fish that have been uploaded to the site. Users are able to sort the top fish by weight/length and species by selecting the desired value from a dropdown menu. Selecting a different option sends a jQuery AJAX request to the backend server API that returns the requested fish catch data in JSON using JBuilder. jQuery then removes the old data and populates the table with the data returned by the API. </p>
                    <p></p>
                </div>
                <div class="col-md-4">
                    <h4>Technical Details</h4>
                    <dl class="row">
                        <dt class="col-md-4">Backend</dt>
                        <dd class="col-md-8">Ruby, Rails, ActiveRecord, AWS S3, Jbuilder </dd>
                        <dt class="col-md-4 text-truncate">Front End</dt>
                        <dd class="col-md-8">JavaScript (jQuery), Bootstrap</dd>
                        <dt class="col-md-4">I Learned</dt>
                        <dd class="col-md-8">This project was an awesome experience using jQuery and Rails. Where appropriate, form data and other requests are sent with AJAX and content is updated without page reloads. </dd>
                    </dl>
                </div>
            </div>
        </div> 
    </div>
    
    <div class="row">
        <div class="jumbotron">
            <h2>Personal Website
                <div class="btn-group pull-right">
                    <%= link_to "Source Code", "https://github.com/Eitansbd/personal_website", target: "_blank", class: "btn btn-primary" %>
                    <%= render 'video_modal', modal_name: "WebsiteModal", youtube_video_id: "TLWLLyii0N8"%>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#WebsiteModal">Demo Video</button>
                </div>
            </h2>
            <div class="row top-buffer-sm">
                <div class="col-md-4">
                    <h4>Background</h4>
                    <p>Looking for a job as a Software Engineer? It's probably a good idea to have a personal website because many jobs will ask for one. Because this project doesn't involve as much backend work, I used it as an oppertunity to learn more about Bootstrap and working with AWS S3 storage as a work around to Heroku's ephemeral filesystem.</p>
                </div>
                <div class="col-md-4">
                    <h4>Best Feature</h4>
                    <p>As the admin, I'm able to sign in and write, post, and edit my blog using markdown syntax. When the post is saved, the title, subtitle, and timestamps are saved to my heroku database along with the S3 object key. When the post is loaded, the S3 object is fetched from the bucket using the object key and the markdown text is rendered using RedCarpet.</p>
                    <p></p>
                </div>
                <div class="col-md-4">
                    <h4>Technical Details</h4>
                    <dl class="row">
                        <dt class="col-md-4">Backend</dt>
                        <dd class="col-md-8">Ruby, Rails, ActiveRecord, AWS S3 </dd>
                        <dt class="col-md-4 text-truncate">Front End</dt>
                        <dd class="col-md-8">HTML/CSS, Bootstrap</dd>
                        <dt class="col-md-4">Challenges</dt>
                        <dd class="col-md-8">Sometimes configuration is the hardest part about a project. Adding the features was easy, figuring out why I couldn't access my S3 buckets was hard.</dd>
                    </dl>
                </div>
            </div>
        </div> 
    </div>
    
    <div class="row">
        <div class="jumbotron">
            <h2>Camp Schedule Management System
                <div class="btn-group pull-right">
                    <%= link_to "Source Code", "https://github.com/Eitansbd/camp_scheduling_app", target: "_blank", class: "btn btn-primary" %>
                    <%= render 'video_modal', modal_name: "Schedular", youtube_video_id: "VGkhKHlJTr0"%>
                    <%= link_to "Project Website", "https://camp-schedule-management.herokuapp.com/", target: "_blank", class: "btn btn-primary" %>
                </div>
            </h2>
            <div class="row top-buffer-sm">
                <div class="col-md-4">
                    <h4>Background</h4>
                    <p class="project-description">The worst job at any summer camp is the scheduler. The app is designed to generate a daily schedule for each bunk in the camp making sure that bunks don't have an activity twice, activities aren't overbooked, double periods are scheduled properly, and a bunch of other requirments. The app is designed to work with the user to make the perfect schedule for each day by allowing for user input at each step in the scheduling proccess.</p>
                </div>
                <div class="col-md-4">
                    <h4>Best Feature</h4>
                    <p>When the user enters a new activity into the system they indicate if the activity should by default be scheduled by the application (for example special activites and trips shouldn't be scheduled by default). Then on the scheduling page they are given a list of all the activities with checkboxes indicating if they are scheduled by default. But the user can uncheck or check any activity and override the default behavior. Unchecking an activity will ensure that the activity isn't scheduled for that day only.</p>
                    <p></p>
                </div>
                <div class="col-md-4">
                    <h4>Technical Details</h4>
                    <dl class="row">
                        <dt class="col-md-4">Backend</dt>
                        <dd class="col-md-8">Ruby, Sinatra, PostgreSQL with custom queries</dd>
                        <dt class="col-md-4 text-truncate">Front End</dt>
                        <dd class="col-md-8">ERB templating and HTML/CSS</dd>
                        <dt class="col-md-4">Challenges</dt>
                        <dd class="col-md-8">I used a custom DAO to interact with the database and had to write a bunch of complicated SQL queries to get the right data while avoiding n+1's</dd>
                    </dl>
                </div>
            </div>
        </div> 
    </div>
    
    <div class="row">
        <div class="jumbotron">
            <h2>Todo App
                <div class="btn-group pull-right">
                    <%= link_to "Source Code", "https://github.com/Eitansbd/rails-todo-app", target: "_blank", class: "btn btn-primary" %>
                    <%= render 'video_modal', modal_name: "Todo", youtube_video_id: "4ZfZ8MTGzGk"%>
                    <%= link_to "Project Website", "https://rails-todo-ebd.herokuapp.com/", target: "_blank", class: "btn btn-primary" %>
                </div>
            </h2>
            <div class="row top-buffer-sm">
                <div class="col-md-4">
                    <h4>Background</h4>
                    <p>For a project at Launch School we had to build a Todo application with sinatra. I decided to convert the app to rails - see the steps I took in this set of <%= link_to "blog posts", blog_post_path(6)%>.</p>
                </div>
                <div class="col-md-4">
                    <h4>Best Feature</h4>
                    <p>Todo apps are fairly common - this one adds some extra features like marking all todos in a list as complete with one button and style changes when items and lists are complete to spice things up a bit.</p>
                    <p></p>
                </div>
                <div class="col-md-4">
                    <h4>Technical Details</h4>
                    <dl class="row">
                        <dt class="col-md-4">Backend</dt>
                        <dd class="col-md-8">Ruby, Rails, ActiveRecord</dd>
                        <dt class="col-md-4 text-truncate">Front End</dt>
                        <dd class="col-md-8">ERB, Bootstrap</dd>
                    </dl>
                </div>
            </div>
        </div> 
    </div>
    
    <div class="row">
        <div class="jumbotron">
            <h2>Pediatric Knee Exoskeleton
                <div class="btn-group pull-right">
                    <%= render 'video_modal', modal_name: "Exo", youtube_video_id: "rV75m7shWj0"%>    
                </div>
            </h2>
            <div class="row top-buffer-sm">
                <div class="col-md-4">
                    <h4>Background</h4>
                    <p>For my advanced mechatronics my group and I (I led the software team) built a pediatric knee exoskeleton for our professor's lab. We used pressure sensors, an arduino, and a low torque density motor to build a working prototype in the limited time we had.</p>
                </div>
                <div class="col-md-4">
                    <h4>Best Feature</h4>
                    <p>The exo is programmed to dynamically update the user's gait cycle time by calculating the average gait over the last three steps. If the user speeds up or slows down the exo will too, just don't go from running to walking in a second.</p>
                    <p></p>
                </div>
                <div class="col-md-4">
                    <h4>Technical Details</h4>
                    <dl class="row">
                        <dt class="col-md-4">Software:</dt>
                        <dd class="col-md-8">Arduino IDE (C/C++) </dd>
                    </dl>
                </div>
            </div>
        </div> 
    </div>
</div>